version: '3'
services:
  api:
    build: .

  relay:
    build:
      context: .
      dockerfile: Dockerfile-relay
    environment:
      RELAY_HOST: api
      RELAY_PORT: 8000
    ports:
      - "8001:8001"
    volumes:

  mysql:
    image: mysql

volumes:
